[package]
name = "to-mut"
version = "0.1.0"
edition = "2021"
description = "Convert immutable reference to mutable reference."
license = "MIT"

[dependencies]
to-mut-proc-macro = { version = "0.1.0" }
